[workspace]
members = [
    "faux-mgs",
    "gateway-messages",
    "gateway-sp-comms",
]

default-members = [
    "faux-mgs",
    "gateway-messages",
    "gateway-sp-comms",
]
resolver = "2"

[workspace.dependencies]
# TODO: Replace with real nix after https://github.com/nix-rust/nix/pull/1973 is
# published to crates.io
nix = { git = "https://github.com/jgallagher/nix", branch = "r0.26-illumos" }

tlvc = {git = "https://github.com/oxidecomputer/tlvc.git"}

anyhow = "1.0"
async-trait = "0.1"
backoff = { version = "0.4.0", features = ["tokio"] }
bitflags = "1.3.2"
clap = { version = "4.0", features = ["derive"] }
futures = "0.3.24"
fxhash = "0.2.1"
glob = "0.3.1"
hex = "0.4.3"
hubpack = "0.1.2"
lru-cache = "0.1.2"
once_cell = "1.15.0"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-big-array = "0.5.0"
serde_json = "1.0.95"
serde_repr = { version = "0.1" }
sha2 = "0.10"
slog = { version = "2.7", features = ["max_level_trace", "release_max_level_trace"] }
slog-async = "2.6"
slog-term = "2.9"
smoltcp = { version = "0.9", default-features = false, features = ["proto-ipv6"] }
socket2 = "0.5.1"
static_assertions = "1.1.0"
string_cache = "0.8.4"
termios = "0.3"
thiserror = "1.0.37"
tokio = { version = "1.21", features = ["full"] }
tokio-stream = { version = "0.1", features = ["fs"] }
tokio-util = { version = "0.7", features = ["compat"] }
usdt = "0.3.1"
uuid = { version = "1.1", default-features = false }
version_check = "0.9.4"
zerocopy = "0.6.1"
zip = { version = "0.6.2", default-features = false, features = ["deflate","bzip2"] }

gateway-messages.path = "gateway-messages"
gateway-sp-comms.path = "gateway-sp-comms"
