[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
anyhow.workspace = true
camino.workspace = true
clap.workspace = true
omicron-zone-package.workspace = true
tokio.workspace = true
